### forgot Password
POST http://localhost:3000/api/auth/forgot-password
Content-Type: application/json

{
  "email": "mithaishop475@gmail.com"
}

### reset Password
POST http://localhost:3000/api/auth/reset-password
Content-Type: application/json

{
  "userId": 1,
  "token": "b00d9639596eed6af951b25bbee829874a2b20bb2dd2d78261f56202c2a62e1d",
  "newPassword": "Applefruit#12"
}
