### forgot Password
POST http://localhost:3000/api/auth/forgot-password
Content-Type: application/json

{
  "email": "ldmdgwbcb6@ozsaip.com"
}

### reset Password
POST http://localhost:3000/api/auth/reset-password
Content-Type: application/json

{
  "userId": 1,
  "token": "{{reset_token}}",
  "newPassword": "NewStrongP@ssw0rd!"
}
