### Create Product
POST {{baseUrl}}/api/product
Content-Type: application/json

{
  "name": "laddu",
  "unitPrice": 12,
  "pricePerKG": 100
}

### Get All Products (page optional)
GET {{baseUrl}}/api/product?page=1

### Get One Product by ID
GET {{baseUrl}}/api/product/1

### Get One Product by Name
GET {{baseUrl}}/api/product/laddu

### Delete Product by ID
DELETE {{baseUrl}}/api/product/1

### top sales
GET {{baseUrl}}/api/product/top/sales?day=2day
